
services:
  node-app:
    build: .
    container_name: hotel_node
    restart: always
    env_file:
      - .env
    ports:
      - "5002:5002"
    networks:
      - pg_hostel

networks:
  pg_hostel:
    external: true
